[package]
name = "post-archiver"
version = "0.0.0"
edition = "2021"
license = "BSD-3-Clause"
description = "A Unify Archive"
authors = ["xiao-e-yun <a0970323059@gmail.com>"]
repository = "https://github.com/xiao-e-yun/PostArchiver"


[features]
typescript = ["ts-rs"]
ts-rs = ["dep:ts-rs"]

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
chrono = { version = "0.4.38", features = ["serde"] }
ts-rs = { version = "8.1.0", features = ["chrono-impl", "no-serde-warnings"], optional = true }
